# Generated by Django 6.0.5 on 2026-05-29 22:03

import django.core.files.storage
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0026_auto_20230929_1021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('event_type', models.CharField(max_length=20)),
                ('version', models.CharField(default='v_S_01_03_00', max_length=20)),
                ('xml_content', models.TextField()),
                ('status', models.CharField(choices=[('CREATED', 'Criado'), ('VALIDATING', 'Validando'), ('SIGNING', 'Assinando'), ('QUEUED', 'Em fila'), ('SENDING', 'Enviando'), ('SENT', 'Enviado'), ('ERROR', 'Erro'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'esocial_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list, help_text='Lista de tipos de evento para notificar')),
                ('is_active', models.BooleanField(default=True)),
                ('secret_token', models.CharField(blank=True, max_length=64)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esocial_webhook_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(upload_to='arquivos_esocial', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='evento',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_evento', to='esocial.eventos', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/workspace/certificados/'), upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='arquivo',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_arquivo', to='esocial.arquivos', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_evento_error',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_transmissor_eventos_erros', to='esocial.transmissoreventos', verbose_name='Lote/Transmissor (Erro)'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='versao',
            field=models.CharField(choices=[('v_S_01_00_00', 'Versão S-1.0'), ('v_S_01_01_00', 'Versão S-1.1'), ('v_S_01_02_00', 'Versão S-1.2'), ('v_S_01_03_00', 'Versão S-1.3')], default='v_S_01_03_00', max_length=20, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='arquivo',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_arquivo_historico', to='esocial.arquivos', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='transmissor_evento_error',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_transmissor_eventos_erros_historico', to='esocial.transmissoreventos', verbose_name='Transmissores (Erro)'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='versao',
            field=models.CharField(choices=[('v_S_01_00_00', 'Versão S-1.0'), ('v_S_01_01_00', 'Versão S-1.1'), ('v_S_01_02_00', 'Versão S-1.2'), ('v_S_01_03_00', 'Versão S-1.3')], default='v_S_01_03_00', max_length=20, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_certificado', to='esocial.certificados', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='transmissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transmissor', to='esocial.transmissor', verbose_name='Transmissor'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmissoreventosarquivos',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmissoreventosarquivos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transmissor_evento', to='esocial.transmissoreventos'),
        ),
        migrations.AlterField(
            model_name='transmissoreventosarquivos',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by_esocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Criado'), ('PROCESSING', 'Processando'), ('SENT', 'Enviado'), ('PARTIAL', 'Parcial'), ('ERROR', 'Erro')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('events', models.ManyToManyField(blank=True, related_name='batches', to='esocial.event')),
            ],
            options={
                'db_table': 'esocial_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField()),
                ('protocol', models.CharField(max_length=50)),
                ('xml_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='esocial.event')),
            ],
            options={
                'db_table': 'esocial_receipt',
                'ordering': ['-received_at'],
            },
        ),
    ]
